on:
  push:
    branches:
      - main
    paths:
      - "packages/react-native/android/**"
      - "fixtures/unit-native/android/**"
  pull_request:
    paths:
      - "packages/react-native/android/**"
      - "fixtures/unit-native/android/**"

name: Android Integration

jobs:
  ktlint:
    runs-on: ubuntu-latest
    name: Kotlin Lint
    steps:
      - uses: actions/checkout@v4
      - uses: touchlab-lab/ktlint-action-setup@1.0.0
        with:
          ktlint_version: 1.3.1
      - run: ktlint "packages/react-native/android/src/**/*.kt"

  build-new-arch:
    runs-on: ubuntu-latest
    name: Build Android (New Architecture)
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install

      - name: Library Build
        run: pnpm build

      - name: Build Android
        run: cd examples/v0.76.1-new-arch/android && ./gradlew assembleDebug --build-cache && cd ../..
        env:
          HOT_UPDATER_CHANNEL: dev

  build-old-arch:
    runs-on: ubuntu-latest
    name: Build Android (Old Architecture)
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install

      - name: Library Build
        run: pnpm build

      - name: Build Android
        run: cd examples/v0.74.1/android && ./gradlew assembleDebug --build-cache && cd ../..
        env:
          HOT_UPDATER_CHANNEL: dev

  unit-tests:
    runs-on: ubuntu-latest
    name: Android Unit Tests
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Make gradlew executable
        run: chmod +x fixtures/unit-native/android/gradlew

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - run: pnpm install

      - name: Run Android Native Unit Tests
        run: |
          cd fixtures/unit-native
          pnpm test:android
