on:
  push:
    branches:
      - main
    paths:
      - "packages/react-native/android/**"
      - ".github/workflows/integration-android.yml"
  pull_request:
    paths:
      - "packages/react-native/android/**"
      - ".github/workflows/integration-android.yml"

name: Android Integration

jobs:
  ktlint:
    runs-on: ubuntu-latest
    name: Kotlin Lint
    steps:
      - uses: actions/checkout@v4
      - uses: touchlab-lab/ktlint-action-setup@1.0.0
        with:
          ktlint_version: 1.3.1
      - run: ktlint "packages/react-native/android/src/**/*.kt"

  build-new-arch:
    runs-on: ubuntu-latest
    name: Build Android (New Architecture)
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install

      - name: Library Build
        run: pnpm build

      - name: Build Android
        run: cd examples/v0.76.1-new-arch/android && ./gradlew clean assembleDebug --build-cache && cd ../..
        env:
          HOT_UPDATER_CHANNEL: dev

  build-old-arch:
    runs-on: ubuntu-latest
    name: Build Android (Old Architecture)
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install

      - name: Library Build
        run: pnpm build

      - name: Build Android
        run: cd examples/v0.72.11/android && ./gradlew clean assembleDebug --build-cache && cd ../..
        env:
          HOT_UPDATER_CHANNEL: dev
